### ISSUE TITLE
how do you authenticate to HDFS using this plugin?

### ISSUE THREAD

**Issue by aoyawale** [sivasamyk/graylog-plugin-output-webhdfs#2]

**Comment by sivasamyk** [comment]
The plugin currently only supports Pseudo authentication. Option 1 in the following URL https://hadoop.apache.org/docs/r1.0.4/webhdfs.html#Authentication

**Comment by aoyawale** [comment]
do you have plans to use TLS/PKI login or username/password for those using cloudera/hortonworks?
